//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DEF.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDEFListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class DEFBaseListener : IDEFListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDef([NotNull] DEFParser.DefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDef([NotNull] DEFParser.DefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.interopDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteropDefinition([NotNull] DEFParser.InteropDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.interopDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteropDefinition([NotNull] DEFParser.InteropDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDefinition([NotNull] DEFParser.StructDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDefinition([NotNull] DEFParser.StructDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.systemDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSystemDefinition([NotNull] DEFParser.SystemDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.systemDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSystemDefinition([NotNull] DEFParser.SystemDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.struct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct([NotNull] DEFParser.StructContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.struct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct([NotNull] DEFParser.StructContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.system"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSystem([NotNull] DEFParser.SystemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.system"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSystem([NotNull] DEFParser.SystemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.native"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNative([NotNull] DEFParser.NativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.native"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNative([NotNull] DEFParser.NativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.managed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterManaged([NotNull] DEFParser.ManagedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.managed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitManaged([NotNull] DEFParser.ManagedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] DEFParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] DEFParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] DEFParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] DEFParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.funcArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncArgumentList([NotNull] DEFParser.FuncArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.funcArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncArgumentList([NotNull] DEFParser.FuncArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.funcArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncArgument([NotNull] DEFParser.FuncArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.funcArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncArgument([NotNull] DEFParser.FuncArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSpecifier([NotNull] DEFParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSpecifier([NotNull] DEFParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.baseType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseType([NotNull] DEFParser.BaseTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.baseType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseType([NotNull] DEFParser.BaseTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.arraySize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArraySize([NotNull] DEFParser.ArraySizeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.arraySize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArraySize([NotNull] DEFParser.ArraySizeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] DEFParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] DEFParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] DEFParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] DEFParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.void"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoid([NotNull] DEFParser.VoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.void"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoid([NotNull] DEFParser.VoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] DEFParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] DEFParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.char"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChar([NotNull] DEFParser.CharContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.char"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChar([NotNull] DEFParser.CharContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.i8"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterI8([NotNull] DEFParser.I8Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.i8"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitI8([NotNull] DEFParser.I8Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.u8"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterU8([NotNull] DEFParser.U8Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.u8"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitU8([NotNull] DEFParser.U8Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.i16"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterI16([NotNull] DEFParser.I16Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.i16"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitI16([NotNull] DEFParser.I16Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.u16"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterU16([NotNull] DEFParser.U16Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.u16"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitU16([NotNull] DEFParser.U16Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.i32"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterI32([NotNull] DEFParser.I32Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.i32"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitI32([NotNull] DEFParser.I32Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.u32"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterU32([NotNull] DEFParser.U32Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.u32"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitU32([NotNull] DEFParser.U32Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.f32"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF32([NotNull] DEFParser.F32Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.f32"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF32([NotNull] DEFParser.F32Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.f64"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF64([NotNull] DEFParser.F64Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.f64"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF64([NotNull] DEFParser.F64Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] DEFParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] DEFParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.enum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum([NotNull] DEFParser.EnumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.enum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum([NotNull] DEFParser.EnumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointer([NotNull] DEFParser.PointerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointer([NotNull] DEFParser.PointerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.endStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndStatement([NotNull] DEFParser.EndStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.endStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndStatement([NotNull] DEFParser.EndStatementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
