//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DEF.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DEFParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDEFListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDef([NotNull] DEFParser.DefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDef([NotNull] DEFParser.DefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.interopDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteropDefinition([NotNull] DEFParser.InteropDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.interopDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteropDefinition([NotNull] DEFParser.InteropDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.structDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDefinition([NotNull] DEFParser.StructDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.structDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDefinition([NotNull] DEFParser.StructDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.systemDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSystemDefinition([NotNull] DEFParser.SystemDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.systemDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSystemDefinition([NotNull] DEFParser.SystemDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct([NotNull] DEFParser.StructContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct([NotNull] DEFParser.StructContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.system"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSystem([NotNull] DEFParser.SystemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.system"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSystem([NotNull] DEFParser.SystemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.native"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNative([NotNull] DEFParser.NativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.native"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNative([NotNull] DEFParser.NativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.managed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterManaged([NotNull] DEFParser.ManagedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.managed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitManaged([NotNull] DEFParser.ManagedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] DEFParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] DEFParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] DEFParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] DEFParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.funcArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncArgumentList([NotNull] DEFParser.FuncArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.funcArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncArgumentList([NotNull] DEFParser.FuncArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.funcArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncArgument([NotNull] DEFParser.FuncArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.funcArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncArgument([NotNull] DEFParser.FuncArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] DEFParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] DEFParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseType([NotNull] DEFParser.BaseTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseType([NotNull] DEFParser.BaseTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.arraySize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArraySize([NotNull] DEFParser.ArraySizeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.arraySize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArraySize([NotNull] DEFParser.ArraySizeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] DEFParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] DEFParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerLiteral([NotNull] DEFParser.IntegerLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerLiteral([NotNull] DEFParser.IntegerLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.void"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVoid([NotNull] DEFParser.VoidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.void"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVoid([NotNull] DEFParser.VoidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] DEFParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] DEFParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.char"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChar([NotNull] DEFParser.CharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.char"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChar([NotNull] DEFParser.CharContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.i8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI8([NotNull] DEFParser.I8Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.i8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI8([NotNull] DEFParser.I8Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.u8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterU8([NotNull] DEFParser.U8Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.u8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitU8([NotNull] DEFParser.U8Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.i16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI16([NotNull] DEFParser.I16Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.i16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI16([NotNull] DEFParser.I16Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.u16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterU16([NotNull] DEFParser.U16Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.u16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitU16([NotNull] DEFParser.U16Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.i32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI32([NotNull] DEFParser.I32Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.i32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI32([NotNull] DEFParser.I32Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.u32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterU32([NotNull] DEFParser.U32Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.u32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitU32([NotNull] DEFParser.U32Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.f32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF32([NotNull] DEFParser.F32Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.f32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF32([NotNull] DEFParser.F32Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.f64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF64([NotNull] DEFParser.F64Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.f64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF64([NotNull] DEFParser.F64Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] DEFParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] DEFParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum([NotNull] DEFParser.EnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum([NotNull] DEFParser.EnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointer([NotNull] DEFParser.PointerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointer([NotNull] DEFParser.PointerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DEFParser.endStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndStatement([NotNull] DEFParser.EndStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DEFParser.endStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndStatement([NotNull] DEFParser.EndStatementContext context);
}
